"""Dead code agent module."""
from app.dead_code.analyzer import DeadCodeAnalyzer
from app.dead_code.report_generator import DeadCodeReportGenerator
from app.storage.repository_registry import repository_registry

def dead_code_node(
    state
):
    repository = (
        repository_registry.get(
            state[
                "repository_name"
            ]
        )
    )

    if not repository:
        state["answer"] = "Repository not indexed. Please index it first."
        return state

    analyzer = (
        DeadCodeAnalyzer(
            repository
        )
    )

    findings = (
        analyzer.analyze()
    )

    generator = (
        DeadCodeReportGenerator()
    )
    
    report = generator.generate(findings)

    from app.chat.llm_provider import LLMProvider
    llm = LLMProvider()

    prompt = f"""
You are a Senior Software Engineer analyzing a dead code report.

Review the following list of unused functions and methods generated by a static analysis tool.
Provide a professional, easy-to-read summary explaining which parts of the codebase contain the most dead code.
Point out any patterns (e.g., test files, public API methods, exception classes) that might explain why these nodes have no static callers within the repository.
Do not simply list every single function. Instead, group them logically and summarize the key findings.

{report}
"""

    state["answer"] = llm.generate(prompt)

    return state
